maintainer : streambinder
name       : pantheon-default-settings
version    : 5.1.2
release    : 10
source     :
    - https://github.com/elementary/default-settings/archive/5.1.2.tar.gz : 7e488ed4c3599af574e4337b0ed0da68246ac5e65b0b022d72ed569415feebfa
license    : GPL-1.0
component  : desktop.pantheon
summary    : Pantheon default settings
description: |
    Default settings for Pantheon desktop.
rundeps:
    - font-open-sans-ttf
    - font-roboto-mono-ttf
    - light-locker
    - pantheon-files
    - pantheon-terminal
install    : |
    install -Dm 644 overrides/default-settings.gschema.override $installdir/usr/share/glib-2.0/schemas/25_pantheon-default-settings.gschema.override
    install -Dm 644 settings.ini -t $installdir/etc/gtk-3.0/
    install -dm 755 $installdir/etc/skel/.config
    cp -dr --no-preserve='ownership' plank $installdir/etc/skel/.config/
    cp -dr --no-preserve='ownership' profile.d $installdir/etc/
