maintainer : Justin
name       : deepin-wm-switcher
version    : 1.1.9
release    : 1
source     :
    - https://github.com/linuxdeepin/deepin-wm-switcher/archive/1.1.9.tar.gz : 6c1a9931b956c3a73dd20bf598336216c8656250379ace62a3b3b9a170cd323c
license    : GPL-3.0-or-later
component  : desktop.deepin.core
summary    : Deepin window manager monitoring and auto-switching service.
description: |
    Deepin window manager monitoring and auto-switching service.
    It is capable of monitoring the health of the 3D WM and falling back to 2D if bad things happened, and detecting platform capability and choose 2D/3D WM accordingly.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(x11)
    - pkgconfig(xcb-keysyms)
rundeps    :
    - deepin-daemon
    - deepin-metacity
    - deepin-wm
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
