name       : menu-cache
version    : 1.1.0
release    : 1
source     :
    - https://github.com/lxde/menu-cache/archive/1.1.0.tar.gz : 990857aa61a2894730e3749b6bc0f905967eed0c21aa2b62a7694007bdccbe8d
license    : LGPL-2.1
component  : desktop.lxqt
summary    : Library used to read freedesktop.org menus
description: |
    Libmenu-cache is a library creating and utilizing caches to speed up the manipulation for freedesktop.org defined application menus.
    It can be used as a replacement of libgnome-menu of gnome-menus.
builddeps  :
    - pkgconfig(glib-2.0)
    - pkgconfig(libfm-extra)
    - gtk-doc
setup      : |
    %autogen
build      : |
    %make
install    : |
    %make_install
