maintainer : Justin
name       : deepin-system-monitor
version    : 5.0.0
release    : 1
source     :
    - git|https://github.com/linuxdeepin/deepin-system-monitor.git : 5.0.0
license    : GPL-3.0-or-later
component  : desktop.deepin
summary    : A more user-friendly system monitor.
description: |
    Deepin system monitor: a more user-friendly system monitor.
builddeps  :
    - libpcap-devel
    - pkgconfig(dtkwidget)
    - pkgconfig(dtkwm)
    - pkgconfig(libprocps)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xcb-util)
    - pkgconfig(xcb)
    - pkgconfig(xext)
    - pkgconfig(xtst)
    - qt5-tools-devel
rundeps    :
    - deepin-qt5integration
setup      : |
    %qmake PREFIX=%PREFIX% LIB_INSTALL_DIR=%libdir%
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
