name       : switchboard-plug-datetime
version    : 2.1.6
release    : 3
source     :
    - https://github.com/elementary/switchboard-plug-datetime/archive/2.1.6.tar.gz : 3a7523e4de2180ef0780dd82a72bcdc88f75046bc6b0925979bba5ac923a2df5
license    : GPL-3.0
component  : desktop.pantheon
summary    : Switchboard date and time plug
description: |
    Date and time plug for Switchboard which configures system time and date.
builddeps  :
    - pkgconfig(granite)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(switchboard-2.0)
    - meson
    - vala
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
