maintainer : Justin
name       : deepin-dbus-generator
version    : 5.0.0
release    : 1
source     :
    - git|https://github.com/linuxdeepin/go-dbus-generator.git : 5.0.0
license    : GPL-3.0-or-later
component  : desktop.deepin.core
summary    : Convert dbus interfaces to go-lang or qml wrapper code.
description: |
    Convert dbus interfaces to go-lang or qml wrapper code.
builddeps  :
    - deepin-go-lib
    - golang
build      : |
    export GOPATH=/usr/share/gocode
    go build -o out/dbus-generator
install    : |
    install -Dm 0755 ./out/dbus-generator %installroot%/usr/bin/dbus-generator
