maintainer : streambinder
name       : switchboard-plug-printers
version    : 2.1.9
release    : 5
source     :
    - https://github.com/elementary/switchboard-plug-printers/archive/2.1.9.tar.gz : 9ef80bd8c3f304da44127c855849ecb58f0ebf5cc74855604be5e616b8ec2fc1
license    : GPL-3.0
component  : desktop.pantheon
summary    : Switchboard printers plug
description: |
    Printers plug for Switchboard which configures all available printers.
builddeps  :
    - pkgconfig(granite)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(switchboard-2.0)
    - cups-devel
    - vala
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
