maintainer : streambinder
name       : switchboard-plug-pantheon-shell
version    : 2.8.4
release    : 5
source     :
    - https://github.com/elementary/switchboard-plug-pantheon-shell/archive/2.8.4.tar.gz : 9bc23bae7a12dfd1ba2e5a2f6b9e8f961543b36fe13671c16bae4ced8b237836
license    : GPL-3.0
component  : desktop.pantheon
summary    : Switchboard desktop plug
description: |
    Switchboard plug for controlling Pantheon Shell.
builddeps  :
    - pkgconfig(gee-0.8)
    - pkgconfig(gexiv2)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(granite)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(plank)
    - pkgconfig(switchboard-2.0)
    - vala
setup      : |
    %meson_configure -Dlibunity='false'
build      : |
    %meson_build
install    : |
    %meson_install
