name       : xfwm4-themes
version    : 4.10.0
release    : 1
source     :
    - http://archive.xfce.org/src/art/xfwm4-themes/4.10/xfwm4-themes-4.10.0.tar.bz2 : 3214d5f00e9703b5e8c9e7c3287d606dedec7285ceb4d5db332e93ada66fd575
license    : GPL-3.0
summary    : Xfwm Themes
description: |
    Theme set for Xfwm.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install