maintainer : streambinder
name       : wingpanel-indicator-power
version    : 2.2.0
release    : 4
source     :
    - https://github.com/elementary/wingpanel-indicator-power/archive/2.2.0.tar.gz : 2db2ae45a35ddf66c204608cfa3f0aa2eb3154816b6f890cc4d73f903e0bd1a5
license    : GPL-3.0
component  : desktop.pantheon
summary    : Wingpanel power indicator
description: |
    Wingpanel inicator for power settings and informations.
builddeps  :
    - pkgconfig(granite)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gudev-1.0)
    - pkgconfig(libbamf3)
    - pkgconfig(libgtop-2.0)
    - vala
    - wingpanel-devel
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
