name       : xcur2png
version    : 0.7.1
release    : 1
source     :
    - https://github.com/eworm-de/xcur2png/releases/download/0.7.1/xcur2png-0.7.1.tar.gz : bc6a062fdb48615a7159ed56ef3d2011168cd8a9decaf1d8a4e316d3064132c9
license    : GPL-3.0-or-later
component  : multimedia.graphics
summary    : Converter from X cursor to PNG image.
description: |
    xcur2png is a program which let you take PNG image from X cursor, and generate config-file which is reusable by xcursorgen.
builddeps  :
    - pkgconfig(libpng)
    - pkgconfig(xcursor)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
