maintainer : algent-al
name       : python-cairocffi
version    : 1.2.0
release    : 2
source     :
    - https://github.com/Kozea/cairocffi/archive/v1.2.0.tar.gz : 5577944680e771022fd0c58fb2bb1e0a308bf1146c518262ae3f20654fddcae2
homepage   : https://cairocffi.readthedocs.io/en/stable/
license    : BSD-3-Clause
component  : programming.python
summary    : CFFI-based cairo bindings for Python
description: |
    cairocffi is a CFFI-based drop-in replacement for Pycairo, a set of Python bindings and object-oriented API for cairo. Cairo is a 2D vector graphics library with support for multiple backends including image buffers, PNG, PostScript, PDF, and SVG file output.
builddeps  :
    - gdk-pixbuf
    - libcairo
    - numpy
    - pytest-isort
    - pytest-runner
    - python-cffi
    - python-pytest-cov
    - python-pytest-flake8
rundeps    :
    - gdk-pixbuf
    - libcairo
    - python-cffi
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
