name       : gsasl
version    : 1.8.0
release    : 2
source     :
    - ftp://ftp.gnu.org/gnu/gsasl/gsasl-1.8.0.tar.gz : 310262d1ded082d1ceefc52d6dad265c1decae8d84e12b5947d9b1dd193191e5
license    : GPL-3.0
summary    : GNU SASL command line utility
description: |
    GNU SASL is an implementation of the Simple Authentication and Security Layer framework and a few common SASL mechanisms.
    SASL is used by network servers (e.g., IMAP, SMTP) to request authentication from clients, and in clients to authenticate against servers.
builddeps  :
    - pkgconfig(gnutls)
    - pkgconfig(krb5)
    - pkgconfig(libidn)
    - libgcrypt-devel
setup      : |
    %configure --prefix=/usr --with-gssapi-impl=mit
build      : |
    %make
install    : |
    %make_install
