maintainer : streambinder
name       : pantheon-applications-menu
version    : 2.7.1
release    : 13
source     :
    - https://github.com/elementary/applications-menu/archive/2.7.1.tar.gz : 6f62d2474776415517017c3b7f297634c1ca5a5e8ed6c002a639c88f317a00bf
license    : GPL-3.0
component  : desktop.pantheon
summary    : Pantheon applications menu
description: |
    Lightweight and stylish Pantheon app launcher.
builddeps  :
    - pkgconfig(appstream)
    - pkgconfig(gee-0.8)
    - pkgconfig(granite)
    - pkgconfig(gstreamer-plugins-base-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libgnome-menu-3.0)
    - pkgconfig(libhandy-0.0)
    - pkgconfig(libmutter-6)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(libvala-0.48)
    - pkgconfig(libwnck-3.0)
    - pkgconfig(plank)
    - pkgconfig(sqlite3)
    - pkgconfig(switchboard-2.0)
    - pkgconfig(taglib)
    - pkgconfig(wingpanel-2.0)
    - pkgconfig(zeitgeist-2.0)
    - gala-devel
    - plank
    - vala
setup      : |
    %meson_configure -Dwith-unity='false'
build      : |
    %meson_build
install    : |
    %meson_install
    mkdir -p $installdir/usr/share/glib-2.0/schemas/
    mkdir -p $installdir/usr/share/xdg/menus
    install data/io.elementary.desktop.wingpanel.applications-menu.gschema.xml $installdir/usr/share/glib-2.0/schemas/
    install data/pantheon-applications.menu $installdir/usr/share/xdg/menus
