maintainer : Justin
name       : xfce4-session
version    : 4.16.0
release    : 8
source     :
    - http://archive.xfce.org/src/xfce/xfce4-session/4.16/xfce4-session-4.16.0.tar.bz2 : 22f273f212481d71e0b5618c62710cd85f69aea74f5ea5c0093f7918b07d17b7
license    : GPL-2.0
component  : desktop.xfce
summary    : Xfce Session Manager
description: |
    Session manager for the Xfce desktop environment.
builddeps  :
    - pkgconfig(libwnck-3.0)
    - pkgconfig(libxfce4ui-2)
    - pkgconfig(sm)
    - pkgconfig(x11)
    - at-libxfce4util-devel
    - iceauth
rundeps    :
    - xrdb
setup      : |
    %configure
build      : |
    %make
install    : |-
    %make_install
