name       : vscodium
version    : 1.37.1
release    : 7
source     :
    - https://github.com/VSCodium/vscodium/releases/download/1.37.1/codium_1.37.1-1565952268_amd64.deb : 81ab4483808977075d0bdf1ba90a30674c53413c27ef978e25cf0e587cb79b0d
license    : MIT
component  : programming.ide
summary    : Visual Studio Code without MS branding, telemetry and licensing
description: |
    The VSCodium project exists so that you don’t have to download+build from source.
    This project includes special build scripts that clone Microsoft’s vscode repo, run the build commands, and upload the resulting binaries for you to GitHub releases.
    These binaries are licensed under the MIT license.
    Telemetry is disabled.
builddeps  :
    - tar
    - binutils
setup      : |
    mkdir -p $installdir
install    : |
    cd $installdir
    tar xvf $workdir/data.tar.*
    find -type f -name \*.desktop -exec sed -i 's|inode/directory;||g' {} \;
