name       : deepin-screen-recorder
version    : 5.8.0
release    : 2
source     :
    - git|https://github.com/linuxdeepin/deepin-screen-recorder.git : 5.8.0
license    : GPL-3.0-or-later
component  : desktop.deepin
summary    : Default screen recorder application for Deepin.
description: |
    a screen recorder tool, it supports to save the recorded screens as gif or mp4 format. It can select the recorded window automatically or manually by selecting the area. Users just need to start and stop the recording process, and the file will auto save to the desktop.
builddeps  :
    - pkgconfig(dtkwidget)
    - pkgconfig(dtkwm)
    - pkgconfig(libprocps)
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(x11)
    - pkgconfig(xcb-util)
    - pkgconfig(xcb)
    - pkgconfig(xtst)
    - qt5-tools-devel
setup      : |
    %qmake PREFIX=%PREFIX% LIB_INSTALL_DIR=%libdir%
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
