name: goldsmith

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set Python environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
          architecture: x64

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pyyaml
          echo "PYTHONPATH=/opt/hostedtoolcache/Python/3.7.6/x64/lib/python3.7/site-packages" >> $GITHUB_ENV

      - name: Lint codebase
        uses: docker://github/super-linter:v2.2.0

      - name: Run test
        run: |
          make test

  stage:
    needs: [analyze]
    if: success() && github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set Python environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
          architecture: x64

      - name: Setup Go environment
        uses: actions/setup-go@v2-beta

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y parallel jq

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pyyaml
          echo "PYTHONPATH=/opt/hostedtoolcache/Python/3.7.6/x64/lib/python3.7/site-packages" >> $GITHUB_ENV
          sudo ln -sf $(which python) /usr/bin/python3

      # TODO: https://github.com/actions/virtual-environments/issues/1816
      # Install using APT as soon as ubuntu-latest label
      # starts referring to Ubuntu Focal Fossa
      - name: Download and configure libgit2-28
        run: |
          sudo apt install -y libssh2-1-dev libssl-dev zlib1g-dev libncurses5-dev \
            libncursesw5-dev libreadline-dev libsqlite3-dev libgdbm-dev \
            libdb5.3-dev libbz2-dev libexpat1-dev liblzma-dev libffi-dev \
            python heimdal-dev libcurl4-openssl-dev cmake
          wget https://github.com/libgit2/libgit2/releases/download/v0.28.5/libgit2-0.28.5.tar.gz
          tar xvf libgit2-0.28.5.tar.gz
          cd libgit2-0.28.5
          mkdir build && cd build
          cmake .. -DCMAKE_INSTALL_PREFIX=/usr
          sudo cmake --build . --target install

      - name: Download and configure Solbuild
        run: |
          git clone https://github.com/getsolus/solbuild.git
          cd solbuild
          sudo make build install
          sudo solbuild init -u
          sudo mkdir /etc/solbuild
          sudo echo 'image = "main-x86_64"
          remove_repos = ["Solus"]
          add_repos = ["Local", "Ashtray", "Solus"]

          [repo.Local]
          uri = "'$GITHUB_WORKSPACE'/build"
          local = true
          autoindex = true

          [repo.Ashtray]
          uri = "https://unstable.solus.davidepucci.it/eopkg-index.xml.xz"

          [repo.Solus]
          uri = "https://mirrors.rit.edu/solus/packages/shannon/eopkg-index.xml.xz"
          ' | sudo tee -a /etc/solbuild/theca-x86_64.profile
          echo '[Packager]
          Name=Goldsmith
          Email=theca@davidepucci.it
          ' | sudo tee -a ~/.solus

      - name: Release
        run: |
          make fetch release sync
        env:
          J: 5
          VARIANT: unstable
          GITHUB_TOKEN: ${{ secrets.GH_ACTIONS_THECA }}

  classify:
    needs: [analyze]
    if: success() && github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set Python environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
          architecture: x64

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pyyaml
          echo "PYTHONPATH=/opt/hostedtoolcache/Python/3.7.6/x64/lib/python3.7/site-packages" >> $GITHUB_ENV
          sudo ln -sf $(which python) /usr/bin/python3

      - name: Generate index
        run: |
          make index-table > Index.md

      - name: Upload index as artifact
        uses: actions/upload-artifact@v2-preview
        with:
          name: index
          path: Index.md

      - name: Checkout wiki
        run: |
          git config --global user.email "automatum@davidepucci.it"
          git config --global user.name "Automatum"
          git clone https://github-actions:${TOKEN}@github.com/streambinder/theca.wiki.git
        env:
          TOKEN: ${{ secrets.GH_ACTIONS_THECA }}

      - name: Push index
        run: |
          cd theca.wiki
          mv ../Index.md .
          git add Index.md
          git commit -m "index: flush" || echo 'Nothing to commit'
          git push
