name       : cinnamon-screensaver
version    : 4.2.0
release    : 1
source     :
    - https://github.com/linuxmint/cinnamon-screensaver/archive/4.2.0.tar.gz : 8dee253e12cbd2f30f2c5112a8e5fba62b651733cb56aa327ede939506adf6a0
license    : GPL-2.0
component  : desktop.cinnamon
summary    : Cinnamon screensaver
description: |
    The Cinnamon screen locker and screensaver program.
builddeps  :
    - pkgconfig(cinnamon-desktop)
    - pkgconfig(dbus-glib-1)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libsystemd)
    - pkgconfig(webkit2gtk-4.0)
    - pkgconfig(x11)
    - gnome-common
setup      : |
    %autogen --prefix=/usr --disable-static --libexecdir=/usr/lib64
build      : |
    %make
install    : |
    %make_install
