maintainer : algent-al
name       : python-cairosvg
version    : 2.5.2
release    : 3
source     :
    - https://github.com/Kozea/CairoSVG/archive/2.5.2.tar.gz : 90a8bee8e7984317a21db4e1c6672e1d17266ced060f3bfd88b1dd70b6c422ff
homepage   : https://cairosvg.org/
license    : LGPL-3.0-or-later
component  : programming.python
summary    : CairoSVG is a SVG converter based on Cairo
description: |
    CairoSVG is a SVG converter based on Cairo. It can export SVG files to PDF, PostScript and PNG files.
builddeps  :
    - pytest-runner
    - pytest-isort
    - python-cairocffi
    - python-cssselect2
    - python-defusedxml
    - python-pillow
    - python-pytest-cov
    - python-pytest-flake8
rundeps    :
    - python-cairocffi
    - python-cssselect2
    - python-defusedxml
    - python-pillow
setup      : |
    cp -r cairosvg test_non_regression/cairosvg_reference/
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
